[tool.poetry]
name = "first-bci"
version = "0.1.0"
description = ""
authors = ["WangWilly <s89667654@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
brainflow = "^5.15.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
